### ISSUE TITLE
HTML supplied to Webview as been deprecated. Use the source prop instead.

### ISSUE THREAD

**Issue by JonathanWi** [jerolimov/react-native-showdown#1]

**Comment by skyride99** [comment]
its just a warning you can edit the source code. Make sure  to give the control a height or nothing shows up. 

return <WebView
                source={ {html:html + ''}}
                automaticallyAdjustContentInsets={ automaticallyAdjustContentInsets }
                onNavigationStateChange={ this.onNavigationStateChange.bind(this) }
                style={ style } />;

**Comment by christoph-jerolimov** [comment]
Thanks for the PR @skyride99. Its merged. 👍
