### ISSUE TITLE
Webview in React-Native Deprecated

### ISSUE THREAD

**Issue by mrcptrrmn** [jerolimov/react-native-showdown#14]
I couldn’t use this library, because the `WebView` module is not available anymore in `react-native` and has been migrated to its own module, `react-native-webview`. Would be wonderful if this new package could be imported.

**Comment by christoph-jerolimov** [comment]
Hi @mrcptrrmn , thanks for your message. Please checkout new version 1.0.0, which is now based on `react-native-webview`.
