### ISSUE TITLE
Dynamic Height

### ISSUE THREAD

**Issue by chandlervdw** [jerolimov/react-native-showdown#4]
This is a newbie question but how can I style the Markdown element to have dynamic height? It is inside a scrollview and I want all of the content to be visible... I just don't know how long that content is.

**Comment by christoph-jerolimov** [comment]
Are you still interested in this? Then i will create a small test project, otherwise we can close this, right?

**Comment by chandlervdw** [comment]
@jerolimov a small test project would be helpful!

**Comment by christoph-jerolimov** [comment]
Doesn't the project in the example doesn't help you?

**Comment by christoph-jerolimov** [comment]
Close this for now. Please open an issue with more details if you have still problems with this project. Thank you.
